/*
* generated by Xtext
*/
package org.maschinenstuermer.clojure.ui.outline;

import org.eclipse.xtext.ui.editor.outline.transformer.AbstractDeclarativeSemanticModelTransformer;

/**
 * customization of the default outline structure
 * 
 */
public class ClojureTransformer extends AbstractDeclarativeSemanticModelTransformer {
	
}
