/*
 * generated by Xtext
 */
package org.maschinenstuermer.clojure;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ClojureRuntimeModule extends org.maschinenstuermer.clojure.AbstractClojureRuntimeModule {

}
