/*
* generated by Xtext
*/
package org.maschinenstuermer.clojure.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.maschinenstuermer.clojure.ui.contentassist.AbstractClojureProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ClojureProposalProvider extends AbstractClojureProposalProvider {

	@Override
	public void completeLiteral_Symbol(EObject model, Assignment assignment,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		super.completeLiteral_Symbol(model, assignment, context, acceptor);
		
	}
}
