/*
 * generated by Xtext
 */
package org.maschinenstuermer.clojure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator;
import org.maschinenstuermer.clojure.ui.contentassist.ClojureReferenceProposalCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ClojureUiModule extends org.maschinenstuermer.clojure.ui.AbstractClojureUiModule {
	public ClojureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ReferenceProposalCreator> bindReferenceProposalCreator() {
		return ClojureReferenceProposalCreator.class;
	}
}
