/*
 * generated by Xtext
 */
package org.maschinenstuermer.clojure.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.ui.editor.contentassist.PrefixMatcher;
import org.eclipse.xtext.ui.editor.contentassist.AbstractJavaBasedContentProposalProvider.ReferenceProposalCreator;
import org.eclipse.xtext.ui.wizard.IProjectCreator;
import org.maschinenstuermer.clojure.ui.contentassist.ClojurePrefixMatcher;
import org.maschinenstuermer.clojure.ui.contentassist.ClojureReferenceProposalCreator;
import org.maschinenstuermer.clojure.ui.wizard.CustomClojureProjectCreator;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ClojureUiModule extends org.maschinenstuermer.clojure.ui.AbstractClojureUiModule {
	public ClojureUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
	public Class<? extends ReferenceProposalCreator> bindAbstractJavaBasedContentProposalProvider$ReferenceProposalCreator() {
		return ClojureReferenceProposalCreator.class;
	}
	
	@Override
	public Class<? extends IProjectCreator> bindIProjectCreator() {
		return CustomClojureProjectCreator.class;
	}
	
	@Override
	public Class<? extends PrefixMatcher> bindPrefixMatcher() {
		return ClojurePrefixMatcher.class;
	}
}
